### ISSUE TITLE
arff2pandas is not supported anymore. Could anyone find alternative for this library?

### ISSUE THREAD

**Issue by UlugbekAbdimanabov** [curiousily/Getting-Things-Done-with-Pytorch#19]

**Comment by chuanzhidong** [comment]
> arff2pandas is not supported anymore. Could anyone find alternative for this library? [on Jun 7, 2022](https://github.com/curiousily/Getting-Things-Done-with-Pytorch/issues/19#event-6761724591)

I saw the same problem, did you solve it use any alternatives?

**Comment by chuanzhidong** [comment]
The answer provided by Sagar Dawda can solve the probelm. Sagar suggested to use `scipy.io.arff.`  We can find from this page: https://stackoverflow.com/questions/46401209/how-to-convert-the-arff-object-loaded-from-a-arff-file-into-a-dataframe-format. 
I quote the answer here:

```
import numpy as np
import pandas as pd
from scipy.io.arff import loadarff 

raw_data = loadarff('Training Dataset.arff')
df_data = pd.DataFrame(raw_data[0])
```
